name: Publish NPM packages

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # NPM automation token (skips 2FA)
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:

    # 1. provide Personal Access Token for checkout@v2
    # GITHUB_TOKEN (personal access token) always exists in repositories, does not have to be explicitly added
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

    # 2. setup .npmrc which uses NODE_AUTH_TOKEN
    - name: Setup .npmrc file for publish
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    # 3. configure git user used to push tag
    - name: Configure Git User
      run: |
        git config --global user.email "ci@hubbleprotocol.io"
        git config --global user.name "ci@$GITHUB_ACTOR"

    - name: Install dependencies
      run: npm ci

    - name: Build packages
      run: lerna run build

    - name: Publish
      run: |
        lerna publish --yes --no-verify-access patch
